services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-auth-challenge'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - /home/arthur/www/Courses/python_rocketseat/module_4_flask-auth/mysql-challenge:/var/lib/mysql